name: Build RocksDB tools (ldb and sst_dump).
on:
  push:
    branches:
    - master
jobs:
  build-and-test-rocksdb-tools:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Build
      run: |
        docker build -t "rocksdb-tools:latest" ./rocksdb-tools
        docker image ls
    - name: Test ldb and sst_dump
      run: |
        docker run --rm -v $PWD/db:/db rocksdb-tools:latest ldb --db=/db --create_if_missing put a1 b1
        docker run --rm -v $PWD/db:/db rocksdb-tools:latest ldb --db=/db get a1
        docker run --rm -v $PWD/db:/db rocksdb-tools:latest ldb --db=/db scan
        docker run --rm -v $PWD/db:/db rocksdb-tools:latest ldb --db=/db scan --hex
        docker run --rm -v $PWD/db:/db rocksdb-tools:latest ldb --db=/db put --key_hex 0x6132 b2
        docker run --rm -v $PWD/db:/db rocksdb-tools:latest ldb --db=/db scan
        docker run --rm -v $PWD/db:/db rocksdb-tools:latest ldb --db=/db get --value_hex a2
        docker run --rm -v $PWD/db:/db rocksdb-tools:latest ldb --db=/db get --hex 0x6131
        docker run --rm -v $PWD/db:/db rocksdb-tools:latest ldb --db=/db batchput a3 b3 a4 b4
        docker run --rm -v $PWD/db:/db rocksdb-tools:latest ldb --db=/db scan
        docker run --rm -v $PWD/db:/db rocksdb-tools:latest ldb --db=/db batchput "multiple words key" "multiple words value"
        docker run --rm -v $PWD/db:/db rocksdb-tools:latest ldb --db=/db scan
        ls -l $PWD/db
        docker run --rm -v $PWD/db:/db rocksdb-tools:latest sst_dump --file=/db/ --command=scan
